import { Animal, GameMode } from "@/types";

// NOTE: Sound URLs are placeholders - replace with actual working URLs from:
// - https://mixkit.co/free-sound-effects/animals/
// - https://freesound.org/ (check licenses)
// - Other free sound libraries

// Animal data with placeholder images and sounds
export const ANIMALS: Animal[] = [
  {
    id: 1,
    name: "Dog",
    emoji: "🐕",
    image: "https://picsum.photos/seed/dog/200/200",
    soundUrl: "https://assets.mixkit.co/active_storage/sfx/1/1-preview.mp3",
    modes: ["byName", "bySound"],
  },
  {
    id: 2,
    name: "Cat",
    emoji: "🐈",
    image: "https://picsum.photos/seed/cat/200/200",
    soundUrl: "https://assets.mixkit.co/active_storage/sfx/93/93-preview.mp3",
    modes: ["byName", "bySound"],
  },
  {
    id: 3,
    name: "Lion",
    emoji: "🦁",
    image: "https://picsum.photos/seed/lion/200/200",
    soundUrl: "https://assets.mixkit.co/active_storage/sfx/6/6-preview.mp3",
    modes: ["byName", "bySound"],
  },
  {
    id: 4,
    name: "Elephant",
    emoji: "🐘",
    image: "https://picsum.photos/seed/elephant/200/200",
    modes: ["byName"],
  },
  {
    id: 5,
    name: "Giraffe",
    emoji: "🦒",
    image: "https://picsum.photos/seed/giraffe/200/200",
    modes: ["byName"],
  },
  {
    id: 6,
    name: "Monkey",
    emoji: "🐒",
    image: "https://picsum.photos/seed/monkey/200/200",
    soundUrl: "https://assets.mixkit.co/active_storage/sfx/108/108-preview.mp3",
    modes: ["byName", "bySound"],
  },
  {
    id: 7,
    name: "Penguin",
    emoji: "🐧",
    image: "https://picsum.photos/seed/penguin/200/200",
    modes: ["byName"],
  },
  {
    id: 8,
    name: "Zebra",
    emoji: "🦓",
    image: "https://picsum.photos/seed/zebra/200/200",
    modes: ["byName"],
  },
  {
    id: 9,
    name: "Tiger",
    emoji: "🐅",
    image: "https://picsum.photos/seed/tiger/200/200",
    modes: ["byName"],
  },
  {
    id: 10,
    name: "Rabbit",
    emoji: "🐰",
    image: "https://picsum.photos/seed/rabbit/200/200",
    modes: ["byName"],
  },
  {
    id: 11,
    name: "Rooster",
    emoji: "🐓",
    image: "https://picsum.photos/seed/rooster/200/200",
    soundUrl:
      "https://assets.mixkit.co/active_storage/sfx/2462/2462-preview.mp3",
    modes: ["byName", "bySound"],
  },
  {
    id: 12,
    name: "Cow",
    emoji: "🐄",
    image: "https://picsum.photos/seed/cow/200/200",
    soundUrl:
      "https://assets.mixkit.co/active_storage/sfx/1751/1751-preview.mp3",
    modes: ["byName", "bySound"],
  },
  {
    id: 13,
    name: "Horse",
    emoji: "🐴",
    image: "https://picsum.photos/seed/horse/200/200",
    soundUrl: "https://assets.mixkit.co/active_storage/sfx/85/85-preview.mp3",
    modes: ["byName", "bySound"],
  },
  {
    id: 14,
    name: "Bird",
    emoji: "🐦",
    image: "https://picsum.photos/seed/bird/200/200",
    soundUrl: "https://assets.mixkit.co/active_storage/sfx/17/17-preview.mp3",
    modes: ["byName", "bySound"],
  },
  {
    id: 15,
    name: "Wolf",
    emoji: "🐺",
    image: "https://picsum.photos/seed/wolf/200/200",
    soundUrl:
      "https://assets.mixkit.co/active_storage/sfx/1775/1775-preview.mp3",
    modes: ["byName", "bySound"],
  },
  {
    id: 16,
    name: "Goose",
    emoji: "🦢",
    image: "https://picsum.photos/seed/goose/200/200",
    soundUrl: "https://assets.mixkit.co/active_storage/sfx/20/20-preview.mp3",
    modes: ["byName", "bySound"],
  },
  {
    id: 17,
    name: "Donkey",
    emoji: "🫏",
    image: "https://picsum.photos/seed/donkey/200/200",
    soundUrl:
      "https://assets.mixkit.co/active_storage/sfx/1770/1770-preview.mp3",
    modes: ["byName", "bySound"],
  },
  {
    id: 18,
    name: "Bear",
    emoji: "🐻",
    image: "https://picsum.photos/seed/bear/200/200",
    soundUrl: "https://assets.mixkit.co/active_storage/sfx/309/309-preview.mp3",
    modes: ["byName", "bySound"],
  },
  {
    id: 19,
    name: "Shark",
    emoji: "🦈",
    image: "https://picsum.photos/seed/shark/200/200",
    modes: ["byName"],
  },
  {
    id: 20,
    name: "Turtle",
    emoji: "🐢",
    image: "https://picsum.photos/seed/turtle/200/200",
    modes: ["byName"],
  },
  {
    id: 21,
    name: "Octopus",
    emoji: "🐙",
    image: "https://picsum.photos/seed/octopus/200/200",
    modes: ["byName"],
  },
  {
    id: 22,
    name: "Crab",
    emoji: "🦀",
    image: "https://picsum.photos/seed/crab/200/200",
    modes: ["byName"],
  },
  {
    id: 23,
    name: "Whale",
    emoji: "🐋",
    image: "https://picsum.photos/seed/whale/200/200",
    modes: ["byName"],
  },
  {
    id: 24,
    name: "Dolphin",
    emoji: "🐬",
    image: "https://picsum.photos/seed/dolphin/200/200",
    modes: ["byName"],
  },
  {
    id: 25,
    name: "Snail",
    emoji: "🐌",
    image: "https://picsum.photos/seed/snail/200/200",
    modes: ["byName"],
  },
  {
    id: 26,
    name: "Ant",
    emoji: "🐜",
    image: "https://picsum.photos/seed/ant/200/200",
    modes: ["byName"],
  },
  {
    id: 27,
    name: "Ladybug",
    emoji: "🐞",
    image: "https://picsum.photos/seed/ladybug/200/200",
    modes: ["byName"],
  },
  {
    id: 28,
    name: "Crocodile",
    emoji: "🐊",
    image: "https://picsum.photos/seed/crocodile/200/200",
    modes: ["byName"],
  },
  {
    id: 29,
    name: "Bat",
    emoji: "🦇",
    image: "https://picsum.photos/seed/bat/200/200",
    modes: ["byName"],
  },
  {
    id: 30,
    name: "Parrot",
    emoji: "🦜",
    image: "https://picsum.photos/seed/parrot/200/200",
    modes: ["byName"],
  },
  {
    id: 31,
    name: "Moose",
    emoji: "🦌",
    image: "https://picsum.photos/seed/moose/200/200",
    modes: ["byName"],
  },
  {
    id: 32,
    name: "Llama",
    emoji: "🦙",
    image: "https://picsum.photos/seed/llama/200/200",
    modes: ["byName"],
  },
  {
    id: 33,
    name: "Buffalo",
    emoji: "🐃",
    image: "https://picsum.photos/seed/buffalo/200/200",
    modes: ["byName"],
  },
  {
    id: 34,
    name: "Turkey",
    emoji: "🦃",
    image: "https://picsum.photos/seed/turkey/200/200",
    soundUrl:
      "https://freeanimalsounds.org/wp-content/uploads/2017/07/truthahn.mp3",
    modes: ["byName", "bySound"],
  },
  {
    id: 35,
    name: "Peacock",
    emoji: "🦚",
    image: "https://picsum.photos/seed/peacock/200/200",
    modes: ["byName"],
  },
  {
    id: 36,
    name: "Swan",
    emoji: "🦢",
    image: "https://picsum.photos/seed/swan/200/200",
    modes: ["byName"],
  },
  {
    id: 37,
    name: "Bee",
    emoji: "🐝",
    image: "https://picsum.photos/seed/bee/200/200",
    modes: ["byName"],
  },
  {
    id: 38,
    name: "Caterpillar",
    emoji: "🐛",
    image: "https://picsum.photos/seed/caterpillar/200/200",
    modes: ["byName"],
  },
  {
    id: 39,
    name: "Scorpion",
    emoji: "🦂",
    image: "https://picsum.photos/seed/scorpion/200/200",
    modes: ["byName"],
  },
  {
    id: 40,
    name: "Lobster",
    emoji: "🦞",
    image: "https://picsum.photos/seed/lobster/200/200",
    modes: ["byName"],
  },
  {
    id: 41,
    name: "Seal",
    emoji: "🦭",
    image: "https://picsum.photos/seed/seal/200/200",
    modes: ["byName"],
  },
  {
    id: 42,
    name: "Raccoon",
    emoji: "🦝",
    image: "https://picsum.photos/seed/raccoon/200/200",
    modes: ["byName"],
  },
  {
    id: 43,
    name: "Badger",
    emoji: "🦡",
    image: "https://picsum.photos/seed/badger/200/200",
    modes: ["byName"],
  },
  {
    id: 44,
    name: "Boar",
    emoji: "🐗",
    image: "https://picsum.photos/seed/boar/200/200",
    modes: ["byName"],
  },
  {
    id: 45,
    name: "Camel",
    emoji: "🐪",
    image: "https://picsum.photos/seed/camel2/200/200",
    modes: ["byName"],
  },
  {
    id: 46,
    name: "Chameleon",
    emoji: "🦎",
    image: "https://picsum.photos/seed/chameleon/200/200",
    modes: ["byName"],
  },
  {
    id: 47,
    name: "Flamingo",
    emoji: "🦩",
    image: "https://picsum.photos/seed/flamingo/200/200",
    modes: ["byName"],
  },
  {
    id: 48,
    name: "Gorilla",
    emoji: "🦍",
    image: "https://picsum.photos/seed/gorilla/200/200",
    modes: ["byName"],
  },
  {
    id: 49,
    name: "Kangaroo",
    emoji: "🦘",
    image: "https://picsum.photos/seed/kangaroo/200/200",
    modes: ["byName"],
  },
  {
    id: 50,
    name: "Leopard",
    emoji: "🐆",
    image: "https://picsum.photos/seed/leopard/200/200",
    modes: ["byName"],
  },
  {
    id: 51,
    name: "Sheep",
    emoji: "🐑",
    image: "https://picsum.photos/seed/sheep/200/200",
    soundUrl:
      "https://freeanimalsounds.org/wp-content/uploads/2017/07/schafe.mp3",
    modes: ["byName", "bySound"],
  },
  {
    id: 52,
    name: "Chicken",
    emoji: "🐥",
    image: "https://picsum.photos/seed/chicken/200/200",
    soundUrl:
      "https://freeanimalsounds.org/wp-content/uploads/2017/07/huehner.mp3",
    modes: ["byName", "bySound"],
  },
  {
    id: 53,
    name: "Pig",
    emoji: "🐖",
    image: "https://picsum.photos/seed/pig/200/200",
    soundUrl:
      "https://freeanimalsounds.org/wp-content/uploads/2017/07/schwein.mp3",
    modes: ["byName", "bySound"],
  },
  {
    id: 54,
    name: "Goat",
    emoji: "🐐",
    image: "https://picsum.photos/seed/goat/200/200",
    soundUrl:
      "https://freeanimalsounds.org/wp-content/uploads/2017/07/Ziege.mp3",
    modes: ["byName", "bySound"],
  },
  {
    id: 55,
    name: "Bull",
    emoji: "🐂",
    image: "https://picsum.photos/seed/bull/200/200",
    soundUrl:
      "https://freeanimalsounds.org/wp-content/uploads/2017/07/ochse.mp3",
    modes: ["byName", "bySound"],
  },
  {
    id: 56,
    name: "Duck",
    emoji: "🦆",
    image: "https://picsum.photos/seed/duck/200/200",
    soundUrl:
      "https://freeanimalsounds.org/wp-content/uploads/2017/07/Ente_quackt.mp3",
    modes: ["byName", "bySound"],
  },
  {
    id: 57,
    name: "Lamb",
    emoji: "🐑",
    image: "https://picsum.photos/seed/lamb/200/200",
    soundUrl:
      "https://freeanimalsounds.org/wp-content/uploads/2017/07/schaf.mp3",
    modes: ["byName", "bySound"],
  },
];

// Helper function to filter animals by game mode
export const getAnimalsByMode = (mode: GameMode): Animal[] => {
  return ANIMALS.filter((animal) => animal.modes.includes(mode));
};
