// Auto-generated by scripts/generateTTSAudio.js
// Do not edit manually

import { Language } from "@/types";

/**
 * Prerecorded animal audio file mappings for Ukrainian and Russian
 */
export const PRERECORDED_ANIMAL_AUDIO: Record<string, Record<"uk" | "ru", any>> = {
  Dog: {
    uk: require("@assets/audio/animals/uk/dog.mp3"),
    ru: require("@assets/audio/animals/ru/dog.mp3"),
  },
  Cat: {
    uk: require("@assets/audio/animals/uk/cat.mp3"),
    ru: require("@assets/audio/animals/ru/cat.mp3"),
  },
  Lion: {
    uk: require("@assets/audio/animals/uk/lion.mp3"),
    ru: require("@assets/audio/animals/ru/lion.mp3"),
  },
  Elephant: {
    uk: require("@assets/audio/animals/uk/elephant.mp3"),
    ru: require("@assets/audio/animals/ru/elephant.mp3"),
  },
  Giraffe: {
    uk: require("@assets/audio/animals/uk/giraffe.mp3"),
    ru: require("@assets/audio/animals/ru/giraffe.mp3"),
  },
  Monkey: {
    uk: require("@assets/audio/animals/uk/monkey.mp3"),
    ru: require("@assets/audio/animals/ru/monkey.mp3"),
  },
  Penguin: {
    uk: require("@assets/audio/animals/uk/penguin.mp3"),
    ru: require("@assets/audio/animals/ru/penguin.mp3"),
  },
  Zebra: {
    uk: require("@assets/audio/animals/uk/zebra.mp3"),
    ru: require("@assets/audio/animals/ru/zebra.mp3"),
  },
  Tiger: {
    uk: require("@assets/audio/animals/uk/tiger.mp3"),
    ru: require("@assets/audio/animals/ru/tiger.mp3"),
  },
  Rabbit: {
    uk: require("@assets/audio/animals/uk/rabbit.mp3"),
    ru: require("@assets/audio/animals/ru/rabbit.mp3"),
  },
  Rooster: {
    uk: require("@assets/audio/animals/uk/rooster.mp3"),
    ru: require("@assets/audio/animals/ru/rooster.mp3"),
  },
  Cow: {
    uk: require("@assets/audio/animals/uk/cow.mp3"),
    ru: require("@assets/audio/animals/ru/cow.mp3"),
  },
  Horse: {
    uk: require("@assets/audio/animals/uk/horse.mp3"),
    ru: require("@assets/audio/animals/ru/horse.mp3"),
  },
  Bird: {
    uk: require("@assets/audio/animals/uk/bird.mp3"),
    ru: require("@assets/audio/animals/ru/bird.mp3"),
  },
  Wolf: {
    uk: require("@assets/audio/animals/uk/wolf.mp3"),
    ru: require("@assets/audio/animals/ru/wolf.mp3"),
  },
  Goose: {
    uk: require("@assets/audio/animals/uk/goose.mp3"),
    ru: require("@assets/audio/animals/ru/goose.mp3"),
  },
  Donkey: {
    uk: require("@assets/audio/animals/uk/donkey.mp3"),
    ru: require("@assets/audio/animals/ru/donkey.mp3"),
  },
  Bear: {
    uk: require("@assets/audio/animals/uk/bear.mp3"),
    ru: require("@assets/audio/animals/ru/bear.mp3"),
  },
  Shark: {
    uk: require("@assets/audio/animals/uk/shark.mp3"),
    ru: require("@assets/audio/animals/ru/shark.mp3"),
  },
  Turtle: {
    uk: require("@assets/audio/animals/uk/turtle.mp3"),
    ru: require("@assets/audio/animals/ru/turtle.mp3"),
  },
  Octopus: {
    uk: require("@assets/audio/animals/uk/octopus.mp3"),
    ru: require("@assets/audio/animals/ru/octopus.mp3"),
  },
  Crab: {
    uk: require("@assets/audio/animals/uk/crab.mp3"),
    ru: require("@assets/audio/animals/ru/crab.mp3"),
  },
  Whale: {
    uk: require("@assets/audio/animals/uk/whale.mp3"),
    ru: require("@assets/audio/animals/ru/whale.mp3"),
  },
  Dolphin: {
    uk: require("@assets/audio/animals/uk/dolphin.mp3"),
    ru: require("@assets/audio/animals/ru/dolphin.mp3"),
  },
  Snail: {
    uk: require("@assets/audio/animals/uk/snail.mp3"),
    ru: require("@assets/audio/animals/ru/snail.mp3"),
  },
  Ant: {
    uk: require("@assets/audio/animals/uk/ant.mp3"),
    ru: require("@assets/audio/animals/ru/ant.mp3"),
  },
  Ladybug: {
    uk: require("@assets/audio/animals/uk/ladybug.mp3"),
    ru: require("@assets/audio/animals/ru/ladybug.mp3"),
  },
  Crocodile: {
    uk: require("@assets/audio/animals/uk/crocodile.mp3"),
    ru: require("@assets/audio/animals/ru/crocodile.mp3"),
  },
  Bat: {
    uk: require("@assets/audio/animals/uk/bat.mp3"),
    ru: require("@assets/audio/animals/ru/bat.mp3"),
  },
  Parrot: {
    uk: require("@assets/audio/animals/uk/parrot.mp3"),
    ru: require("@assets/audio/animals/ru/parrot.mp3"),
  },
  Moose: {
    uk: require("@assets/audio/animals/uk/moose.mp3"),
    ru: require("@assets/audio/animals/ru/moose.mp3"),
  },
  Llama: {
    uk: require("@assets/audio/animals/uk/llama.mp3"),
    ru: require("@assets/audio/animals/ru/llama.mp3"),
  },
  Buffalo: {
    uk: require("@assets/audio/animals/uk/buffalo.mp3"),
    ru: require("@assets/audio/animals/ru/buffalo.mp3"),
  },
  Turkey: {
    uk: require("@assets/audio/animals/uk/turkey.mp3"),
    ru: require("@assets/audio/animals/ru/turkey.mp3"),
  },
  Peacock: {
    uk: require("@assets/audio/animals/uk/peacock.mp3"),
    ru: require("@assets/audio/animals/ru/peacock.mp3"),
  },
  Swan: {
    uk: require("@assets/audio/animals/uk/swan.mp3"),
    ru: require("@assets/audio/animals/ru/swan.mp3"),
  },
  Bee: {
    uk: require("@assets/audio/animals/uk/bee.mp3"),
    ru: require("@assets/audio/animals/ru/bee.mp3"),
  },
  Caterpillar: {
    uk: require("@assets/audio/animals/uk/caterpillar.mp3"),
    ru: require("@assets/audio/animals/ru/caterpillar.mp3"),
  },
  Scorpion: {
    uk: require("@assets/audio/animals/uk/scorpion.mp3"),
    ru: require("@assets/audio/animals/ru/scorpion.mp3"),
  },
  Lobster: {
    uk: require("@assets/audio/animals/uk/lobster.mp3"),
    ru: require("@assets/audio/animals/ru/lobster.mp3"),
  },
  Seal: {
    uk: require("@assets/audio/animals/uk/seal.mp3"),
    ru: require("@assets/audio/animals/ru/seal.mp3"),
  },
  Raccoon: {
    uk: require("@assets/audio/animals/uk/raccoon.mp3"),
    ru: require("@assets/audio/animals/ru/raccoon.mp3"),
  },
  Badger: {
    uk: require("@assets/audio/animals/uk/badger.mp3"),
    ru: require("@assets/audio/animals/ru/badger.mp3"),
  },
  Boar: {
    uk: require("@assets/audio/animals/uk/boar.mp3"),
    ru: require("@assets/audio/animals/ru/boar.mp3"),
  },
  Camel: {
    uk: require("@assets/audio/animals/uk/camel.mp3"),
    ru: require("@assets/audio/animals/ru/camel.mp3"),
  },
  Chameleon: {
    uk: require("@assets/audio/animals/uk/chameleon.mp3"),
    ru: require("@assets/audio/animals/ru/chameleon.mp3"),
  },
  Flamingo: {
    uk: require("@assets/audio/animals/uk/flamingo.mp3"),
    ru: require("@assets/audio/animals/ru/flamingo.mp3"),
  },
  Gorilla: {
    uk: require("@assets/audio/animals/uk/gorilla.mp3"),
    ru: require("@assets/audio/animals/ru/gorilla.mp3"),
  },
  Kangaroo: {
    uk: require("@assets/audio/animals/uk/kangaroo.mp3"),
    ru: require("@assets/audio/animals/ru/kangaroo.mp3"),
  },
  Leopard: {
    uk: require("@assets/audio/animals/uk/leopard.mp3"),
    ru: require("@assets/audio/animals/ru/leopard.mp3"),
  },
  Sheep: {
    uk: require("@assets/audio/animals/uk/sheep.mp3"),
    ru: require("@assets/audio/animals/ru/sheep.mp3"),
  },
  Chicken: {
    uk: require("@assets/audio/animals/uk/chicken.mp3"),
    ru: require("@assets/audio/animals/ru/chicken.mp3"),
  },
  Pig: {
    uk: require("@assets/audio/animals/uk/pig.mp3"),
    ru: require("@assets/audio/animals/ru/pig.mp3"),
  },
  Goat: {
    uk: require("@assets/audio/animals/uk/goat.mp3"),
    ru: require("@assets/audio/animals/ru/goat.mp3"),
  },
  Bull: {
    uk: require("@assets/audio/animals/uk/bull.mp3"),
    ru: require("@assets/audio/animals/ru/bull.mp3"),
  },
  Duck: {
    uk: require("@assets/audio/animals/uk/duck.mp3"),
    ru: require("@assets/audio/animals/ru/duck.mp3"),
  },
  Lamb: {
    uk: require("@assets/audio/animals/uk/lamb.mp3"),
    ru: require("@assets/audio/animals/ru/lamb.mp3"),
  },
  Snake: {
    uk: require("@assets/audio/animals/uk/snake.mp3"),
    ru: require("@assets/audio/animals/ru/snake.mp3"),
  },
  Raven: {
    uk: require("@assets/audio/animals/uk/raven.mp3"),
    ru: require("@assets/audio/animals/ru/raven.mp3"),
  },
  Owl: {
    uk: require("@assets/audio/animals/uk/owl.mp3"),
    ru: require("@assets/audio/animals/ru/owl.mp3"),
  },
};

/**
 * Prerecorded UI phrase audio file mappings
 */
export const PRERECORDED_UI_AUDIO: Record<"findThe" | "whoSaysThis", Record<"uk" | "ru", any>> = {
  findThe: {
    uk: require("@assets/audio/ui/uk/findthe.mp3"),
    ru: require("@assets/audio/ui/ru/findthe.mp3"),
  },
  whoSaysThis: {
    uk: require("@assets/audio/ui/uk/whosaysthis.mp3"),
    ru: require("@assets/audio/ui/ru/whosaysthis.mp3"),
  },
};

/**
 * Check if prerecorded audio exists for given language
 */
export const hasPrerecordedAudio = (language: Language): boolean => {
  return language === "uk" || language === "ru";
};
